### ISSUE TITLE
An option for braces perhaps?

### ISSUE THREAD

**Issue by HastaLaVi2** [lkrms/vscode-pretty-php#1]
I want to be able to use this kind of classes:

class className {
...
}

rather than

class className
{
...
}

**Comment by lkrms** [comment]
Thanks for your request, and congratulations on opening the first issue :)

I'd like PrettyPHP to be useful to developers who don't have the luxury of choosing a different coding standard, but I'm also trying to minimise option bloat and provide a consistent, uncompromising baseline for minutiae like brace / parentheses / square bracket placement. It's a tricky balance to find (and there are probably too many options already!)

With `class` and other declaration-related braces (everything except control structures and anonymous functions, basically), PrettyPHP places the opening brace on a new line for consistency with PSR-12 and the coding standards of widely-used projects like Symfony and Laravel, but I'm open to reviewing that.

Is there a particular coding standard you're working with?

And I assume the answer is yes, but would you expect this placement of braces to apply everywhere? (i.e. `function`, `namespace`, etc.)

**Comment by lkrms** [comment]
I just published an update to the extension (v0.3.3) that should do what you need.

1. PrettyPHP now has a `--one-true-brace-style` option. When given, opening braces are placed after `class`, `function`, etc. on the same line.

2. The vscode extension has a new "Formatter Arguments" setting. Add `--one-true-brace-style` to pass the new option to PrettyPHP.

**Comment by HastaLaVi2** [comment]
Thank you so much! You made some new nice features as well.

**Comment by CodeCubeNeo** [comment]
The vscode extension has a new "Formatter Arguments" setting. Add --one-true-brace-style to pass the new option to PrettyPHP. CAN YOU ADD THIS TO THE README AT THE BEGGING. It doesnt say that this is possible anwyare unless in this issue i think. I needed some time to find it, so I think it will be helpful if it were psoted in the readme.
