### ISSUE TITLE
Is this extension compatible with the Official Prettier PHP Plugin?

### ISSUE THREAD

**Issue by trymeouteh** [lkrms/vscode-pretty-php#10]
Is this extension compatible with the Official Prettier PHP Plugin?

https://github.com/prettier/plugin-php

If I used this extension in my editor while another developer using a different editor on their computer and uses the Official Prettier PHP Plugin, would be both have the same formatted PHP code?

**Comment by lkrms** [comment]
Answered here: https://github.com/lkrms/pretty-php/discussions/123
